# Generated by Django 4.2.1 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0002_coupon_subscriptionbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_name',
            new_name='name',
        ),
    ]
