# Generated by Django 4.2.1 on 2024-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0003_rename_discount_percent_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
