# Generated by Django 4.2.1 on 2024-06-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_franklin', '0004_book_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id_contact_message', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'ContactMessages',
                'db_table': 'ContactMessage',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionBook',
        ),
    ]
